# Generated by Django 3.2.3 on 2021-06-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
