# Generated by Django 3.2.3 on 2021-06-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='summary',
            field=models.TextField(max_length=200),
        ),
    ]
