# Generated by Django 3.2.3 on 2021-06-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projects_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='summary',
            field=models.TextField(max_length=500),
        ),
    ]
