# Generated by Django 3.2.3 on 2021-06-22 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projects_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
